# Site settings
title: while42
email: your-email@domain.com
description: French Tech Engineers Network
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://while42.org" # the base hostname & protocol for your site
twitter_username: while_42
github_username:  while42-org

destination: ./_site
layouts:     ./_layouts
data_source: ./_data

exclude:
- vendor
- README.md
- Dockerfile
- .ruby-version
- .bundle

encoding:     "utf-8"

markdown_ext: "md"

# Build settings
markdown: kramdown
